---
sudo: required
services: docker
addons:
  apt:
    packages:
      - docker-ce
matrix:
  include:
  - env: ELASTIC_STACK_VERSION=6.2.4
  - env: ELASTIC_STACK_VERSION=6.4.1
  - env: ELASTIC_STACK_VERSION=7.0.0-alpha1-SNAPSHOT
  fast_finish: true
install: ci/unit/docker-setup.sh
script: ci/unit/docker-run.sh
